version: '2'

volumes:
  mosquitto_data:

services:
  mosquitto:
    container_name: "mosquitto"
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/data
      - /root/docker-config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf # with correspond path
