version: '2'

volumes:
  qbittorrent_data:
  qbittorrent_config:

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=10090
    volumes:
      - qbittorrent_config:/config
      - qbittorrent_data:/downloads
    ports:
      - 10080:10090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
