version: '3'

volumes:
    v2raya_data:

services:
    v2raya:
        restart: always
        privileged: true
        container_name: v2raya
        environment:
            - V2RAYA_LOG_FILE=/tmp/v2raya.log
            - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
            - V2RAYA_NFTABLES_SUPPORT=on # 启用 nft tables 支持， 如果设置为 off，则下一项需要指定 iptables 或者 legacy
            # - IPTABLES_MODE=iptables
        volumes:
            - /lib/modules:/lib/modules:ro
            - /etc/resolv.conf:/etc/resolv.conf
            - v2raya_data:/etc/v2raya
        ports:
            - "2017:2017"
            - "20170-20173:20170-20173"
        image: mzz2017/v2raya
