version: '2'

volumes:
  nextcloud_data:
  db_data:
  frps_config:
    driver: local
    driver_opts:
      type: none
      device: /root/docker-config/frp/frps.ini #NOTE needs full path (~ doesn't work)
      o: bind

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --performance_schema=False
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nopepsi
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      
  nextcloud:
    image: nextcloud_data:production-apache
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nopepsi
      - MYSQL_HOST=db

  frps:
    images: snowdreamtech/frps
    restart: always
    network_mode: "host"
    volumes:
      - frps_config:/etc/frp/frps.ini
