version: '2'

volumes:
  nextcloud_data:
  db_data:

services:
  mariadb:
    container_name: "mariadb"
    image: mariadb:10.11.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --performance_schema=False --bind-address=0.0.0.0
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - /root/docker-config/mariadb/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql # database init sql
    environment:
      - MYSQL_ROOT_PASSWORD= # recommend only number and a-z, A-Z
      - MYSQL_PASSWORD= # recommend only number and a-z, A-Z
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nopepsi
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      
  nextcloud:
    container_name: "nextcloud"
    image: nextcloud:stable-apache
    restart: always
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD= # stay with the above setting
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nopepsi
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_HOSTNAME= # ip address or host name
      
  homeassistant:
    container_name: "homeassistant"
    image: ghcr.nju.edu.cn/home-assistant/home-assistant:stable
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mariadb
    volumes:
      - /root/docker-config/homeassistant:/config # fill with correspond location on server
    restart: unless-stopped
    privileged: true
    network_mode: host

  frps:
    container_name: "frps"
    image: snowdreamtech/frps:0.51.3
    restart: always
    network_mode: "host"
    volumes:
      - /root/docker-config/frp/frps.ini:/etc/frp/frps.ini # fill with correspond location on server
