version: '2'

volumes:
  nextcloud_data:
  db_data:

services:
  mariadb:
    container_name: "mariadb"
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --performance_schema=False
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nopepsi
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      
  nextcloud:
    container_name: "nextcloud"
    image: nextcloud_data:production-apache
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nopepsi
      - MYSQL_HOST=db

  frps:
    container_name: "frps"
    images: snowdreamtech/frps
    restart: always
    network_mode: "host"
    volumes:
      - /root/docker-config/frp/frps.ini:/etc/frp/frps.ini

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
